In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
A = np.array([[2, 3, 4],
              [10, 20, 30]])

B = np.array([[2, 3, 4],
              [10, 20, 30]], dtype = np.float32)
#모든 matrix 는 float 으로 잡음. 계산된 결과가 정수이기가 힘들기 때문에
#값이 저장이 안됨. 

print("Matrix A = \n", A)
print("Shape of A = ", A.shape)
print("Dtype of A = ", A.dtype)

print("Matrix B = \n", B)
print("Shape of B = ", B.shape)
print("Dtype of B = ", B.dtype)

print(np.__version__)

Matrix A = 
 [[ 2  3  4]
 [10 20 30]]
Shape of A =  (2, 3)
Dtype of A =  int64
Matrix B = 
 [[ 2.  3.  4.]
 [10. 20. 30.]]
Shape of B =  (2, 3)
Dtype of B =  float32
2.0.0


In [5]:
# Diagonal Matrix

a = np.array([1,2,3,4,5])
D_1 = np.diag(a)
print("D_1 = \n", D_1)

b = np.random.randint(1,10,5)
D_2 = np.diag(b)
print("D_2 = \n", D_2)

D_1 = 
 [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
D_2 = 
 [[3 0 0 0 0]
 [0 8 0 0 0]
 [0 0 3 0 0]
 [0 0 0 1 0]
 [0 0 0 0 6]]


In [6]:
# Identitiy 단위행렬

I_3 = np.eye(3)
print("3 x 3 Identity = \n", I_3)


I_5 = np.eye(5)
print("5 x 5 Identity = \n", I_5)


3 x 3 Identity = 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
5 x 5 Identity = 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
##전치 행렬, Matrix Transpose 
A = np.array([[1,2,3,4],
              [5,6,7,8]], dtype = np.int64)

print("A = \n", A)
print("transpose A = \n", A.T) 

A = 
 [[1 2 3 4]
 [5 6 7 8]]
transpose A = 
 [[1 5]
 [2 6]
 [3 7]
 [4 8]]
